import requests
import json

url = "http://knowledge-engine.easygov.co.in:1880/getInferenceGraphData?file_name=Test_weightage_InferenceGraph.json"

payload={}
headers = {}

response = requests.get(url, headers=headers, data=payload)

response = json.loads(response.text)

print(response)


{'nodes': [{'id': 'HouseBenefit',
   'type': 'INFO',
   'group': 1,
   'label': '',
   'text': '',
   'pieChart': [{'color': 0, 'percent': 50, 'value': 'Yes'},
    {'color': 1, 'percent': 50, 'value': 'No'}],
   'CPTDEFINED': 1,
   'PTABLE': [{'Row': 1, 'data': ['Low', 'low', 'Low', '1', '0']},
    {'Row': 2, 'data': ['Low', 'low', 'High', '0.62', '0.38']},
    {'Row': 3, 'data': ['Low', 'medium', 'Low', '0.88', '0.12']},
    {'Row': 4, 'data': ['Low', 'medium', 'High', '0.5', '0.5']},
    {'Row': 5, 'data': ['Low', 'High', 'Low', '0.76', '0.24']},
    {'Row': 6, 'data': ['Low', 'High', 'High', '0.38', '0.62']},
    {'Row': 7, 'data': ['High', 'low', 'Low', '0.62', '0.38']},
    {'Row': 8, 'data': ['High', 'low', 'High', '0.24', '0.76']},
    {'Row': 9, 'data': ['High', 'medium', 'Low', '0.5', '0.5']},
    {'Row': 10, 'data': ['High', 'medium', 'High', '0.12', '0.88']},
    {'Row': 11, 'data': ['High', 'High', 'Low', '0.38', '0.62']},
    {'Row': 12, 'data': ['High', 'High', 'High', '0', '1']}],
   'CPT': [[1, 0],
    [0.62, 0.38],
    [0.88, 0.12],
    [0.5, 0.5],
    [0.76, 0.24],
    [0.38, 0.62],
    [0.62, 0.38],
    [0.24, 0.76],
    [0.5, 0.5],
    [0.12, 0.88],
    [0.38, 0.62],
    [0, 1]],
   'INP': 'translate(298,398)'},
  {'id': 'HouseTyp',
   'type': '',
   'group': 2,
   'label': '',
   'text': '',
   'pieChart': [{'color': 0, 'percent': 50, 'value': 'Low'},
    {'color': 1, 'percent': 50, 'value': 'High'}],
   'CPTDEFINED': 1,
   'PTABLE': [{'Row': 1, 'data': ['0.4', '0.6']}],
   'CPT': [[0.4, 0.6]],
   'INP': 'translate(98,124.5)'},
  {'id': 'HouseVal',
   'type': 'INFO',
   'group': 2,
   'label': '',
   'text': '',
   'pieChart': [{'color': 0, 'percent': 33.333333333333336, 'value': 'low'},
    {'color': 1, 'percent': 33.333333333333336, 'value': 'medium'},
    {'color': 2, 'percent': 33.333333333333336, 'value': 'High'}],
   'CPTDEFINED': 1,
   'PTABLE': [{'Row': 1, 'data': ['0.2', '0.5', '0.3']}],
   'CPT': [[0.2, 0.5, 0.3]],
   'INP': 'translate(252,219.5)'},
  {'id': 'AmenitiesProf',
   'type': 'INFO',
   'group': 2,
   'label': '',
   'text': '',
   'pieChart': [{'color': 0, 'percent': 50, 'value': 'Low'},
    {'color': 1, 'percent': 50, 'value': 'High'}],
   'CPTDEFINED': 1,
   'PTABLE': [{'Row': 1, 'data': ['Yes', 'Yes', '0', '1']},
    {'Row': 2, 'data': ['Yes', 'No', '0.4', '0.6']},
    {'Row': 3, 'data': ['No', 'Yes', '0.6', '0.4']},
    {'Row': 4, 'data': ['No', 'No', '1', '0']}],
   'CPT': [[0, 1], [0.4, 0.6], [0.6, 0.4], [1, 0]],
   'INP': 'translate(419,148.5)'},
  {'id': 'Toilet',
   'type': '',
   'group': 3,
   'label': '',
   'text': '',
   'pieChart': [{'color': 0, 'percent': 50, 'value': 'Yes'},
    {'color': 1, 'percent': 50, 'value': 'No'}],
   'CPTDEFINED': 1,
   'PTABLE': [{'Row': 1, 'data': ['0.9', '0.1']}],
   'CPT': [[0.9, 0.1]],
   'INP': 'translate(195,20)'},
  {'id': 'Electrified',
   'type': '',
   'group': 3,
   'label': '',
   'text': '',
   'pieChart': [{'color': 0, 'percent': 50, 'value': 'Yes'},
    {'color': 1, 'percent': 50, 'value': 'No'}],
   'CPTDEFINED': 1,
   'PTABLE': [{'Row': 1, 'data': ['0.8', '0.2']}],
   'CPT': [[0.8, 0.2]],
   'INP': 'translate(422,9)'}],
 'links': [{'source': 'HouseTyp', 'target': 'HouseBenefit', 'value': 5},
  {'source': 'HouseVal', 'target': 'HouseBenefit', 'value': 5},
  {'source': 'AmenitiesProf', 'target': 'HouseBenefit', 'value': 5},
  {'source': 'Toilet', 'target': 'AmenitiesProf', 'value': 5},
  {'source': 'Electrified', 'target': 'AmenitiesProf', 'value': 5}]}

